from pyautogui import write, hotkey
from time import sleep as wait
from unidecode import unidecode
arr = ["Street by Street", "Someone New", "Street by Street", "Magnolia", "Like the Movies", "I Wish You Love", "James", "Someone New", "Best Friend", "Let You Break My Heart Again", "Love Flew Away", "Love To Keep Me Warm", "Valentine", "Everything I Know About Love", "Valentine - Live", "Falling Behind - Live", "Dear Soulmate - Live", "Fragile - Live", "Let You Break My Heart Again - Live", "Everything I Know About Love - Live", "Fragile", "Beautiful Stranger", "Valentine", "Above The Chinese Restaurant", "Dear Soulmate", "What Love Will Do to You", "I've Never Been In Love Before", "Just Like Chet", "Everything I Know About Love", "Falling Behind", "Hi", "Dance With You Tonight", "Night Light", "Slow Down", "Lucky for Me", "Questions For The Universe", "Ain't Christmas", "Valentine - Live at The Symphony", "Fragile - Live at The Symphony", "Valentine - Live at The Symphony", "Dear Soulmate - Live at The Symphony", "I Wish You Love - Live at The Symphony", "Night Light - Live at The Symphony", "Ég Veit Þú Kemur - Live at The Symphony", "Falling Behind - Live at The Symphony", "Best Friend - Live at The Symphony", "Like the Movies - Live at The Symphony", "The Nearness of You - Live at The Symphony", "Let You Break My Heart Again - Live at The Symphony", "What Love Will Do to You - Live at The Symphony", "Beautiful Stranger - Live at The Symphony", "Everytime We Say Goodbye - Live at The Symphony", "From The Start", "This Is How It Feels (with Laufey)", "Dreamer", "Second Best", "Haunted", "Must Be Love", "While You Were Sleeping", "Lovesick", "California and Me", "Nocturne (Interlude)", "Promise", "From The Start", "Misty", "Serendipity", "Letter To My 13 Year Old Self", "Bewitched", "No One Knows (with Laufey)", "A Night To Remember", "Winter Wonderland", "Christmas Dreaming", "The Christmas Waltz", "Love to Keep Me Warm", "Have Yourself A Merry Little Christmas", "Better Than Snow", "Winter Wonderland", "Goddess", "Dreamer", "Second Best", "Haunted", "Must Be Love", "While You Were Sleeping", "Lovesick", "California and Me", "Nocturne (Interlude)", "Promise", "From The Start", "Misty", "Serendipity", "Letter To My 13 Year Old Self", "Bewitched", "Bored", "Trouble", "It Could Happen To You", "Goddess", "Bewitched - Rework"]
print("starting in 2.5 seconds")
wait(2.5)
for i in range(len(arr)):
    string = unidecode(arr[i]).lower()
    write(string) #, interval=(0.05/len(string))
    hotkey("ctrl", "a")